sudo: required

services:
  - docker

## Make sure all containers build without error.
before_install: 
  - docker build -t rocker/r-base r-base
  - docker build -t rocker/rstudio rstudio
  - docker build -t pconwell/rstudio
  
## A few simple / crude tests
script:
  - docker run -d --name rstudio pconwell/rstudio
  - sleep 5 && docker ps | grep rstudio
  - docker rm -f $(docker ps -a -q)
